#!/bin/sh

HTTP_USER=www-data
# Set the group
find . -not -group ${HTTP_USER} -exec chgrp -v ${HTTP_USER} {} \;
# Give the group and other read/execute for all directories
find . -type d -not -wholename './_*' -not -perm 755 -exec chmod -v 755 {} \;
find . -type d -wholename './_*' -not -perm 775 -exec chmod -v 775 {} \;
# Give the group and other read for all files
find . -type f -not -wholename './_*' -not -perm 644 -exec chmod -v 644 {} \;
find . -type f -wholename './_*' -not -perm 664 -exec chmod -v 664 {} \;
# fix ourself
chmod +x $0

